export type ScoreInputs = {
  excl: number;
  pol: number;
  bdiv: number;
  ceo: number;
  whistleblower: number;
  audit_quality: number;
  transparency: number;
  ai_governance: number;
  data_ethics: number;
  algo_bias: number;
  data_privacy: number;
  model_robustness: number;
  explainability: number;
  egy: number;
  wat: number;
  circ: number;
  crm: number;
  ghg: number;
  biodiversity: number;
  renewable_pct: number;
  ghg_intensity: number;
  du: number;
  wpn: number;
  hr: number;
  rri: number;
  safety_testing: number;
  primary_sdg: number;
  soc: number;
  stakeholder: number;
  inclusion: number;
  impact_scale: number;
  impact_additionality: number;
  job_impact: number;
  fin_runway: number;
  fin_quality: number;
  revenue_model: number;
  valuation: number;
  mkt_tam: number;
  competitive: number;
  customer_conc: number;
  regulatory_env: number;
  tech_moat: number;
  scalability: number;
  data_quality: number;
  cybersecurity: number;
  ip_portfolio: number;
  hw_lifespan: number;
  team_exec: number;
  theme_fit: number;
  key_person: number;
  advisory: number;
  legal_structure: number;
  regulatory_compliance: number;
  litigation: number;
  concentration_risk: number;
  operational_risk: number;
  exit_feasibility: number;
};

export const DEFAULT_SCORE_INPUTS: ScoreInputs = {
  excl: 0,
  pol: 72,
  bdiv: 40,
  ceo: 0,
  whistleblower: 3,
  audit_quality: 3,
  transparency: 3,
  ai_governance: 3,
  data_ethics: 3,
  algo_bias: 2,
  data_privacy: 3,
  model_robustness: 3,
  explainability: 3,
  egy: 3,
  wat: 2,
  circ: 3,
  crm: 0,
  ghg: 3,
  biodiversity: 3,
  renewable_pct: 3,
  ghg_intensity: 3,
  du: 10,
  wpn: 1,
  hr: 1,
  rri: 18,
  safety_testing: 3,
  primary_sdg: 7,
  soc: 4,
  stakeholder: 3,
  inclusion: 3,
  impact_scale: 3,
  impact_additionality: 3,
  job_impact: 3,
  fin_runway: 3,
  fin_quality: 3,
  revenue_model: 3,
  valuation: 3,
  mkt_tam: 3,
  competitive: 3,
  customer_conc: 2,
  regulatory_env: 3,
  tech_moat: 3,
  scalability: 3,
  data_quality: 3,
  cybersecurity: 3,
  ip_portfolio: 3,
  hw_lifespan: 3,
  team_exec: 3,
  theme_fit: 3,
  key_person: 2,
  advisory: 3,
  legal_structure: 3,
  regulatory_compliance: 3,
  litigation: 1,
  concentration_risk: 2,
  operational_risk: 3,
  exit_feasibility: 3,
};
